name: Ejercicio 1

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir nombre
        run: echo "Hola, mi nombre es Jorge Ariel Espinal"

      - name: Imprimir fecha y hora actual
        run: date

      - name: Imprimir sistema operativo del runner
        run: echo "Sistema operativo: $RUNNER_OS"